# MirStatus - to publish data on a topic
int32  state    			# system state
string  mode    			# overall operation of the robot
string  msg     			# status message
float32 uptime  			# time since start in min
float32 moved   			# combined distance moved since last start
float32 battery 			# voltage of battery
float32 battery_percentage 		# battery left in percent
int32 battery_time_left 		# battery time left in seconds
float32 eta     			# estimated time of arrival (not impl)
