FROM ros:noetic-ros-core

# python3-osrf-pycommon has to be installed manually for python3-catkin-tools to work (see https://github.com/catkin/catkin_tools/issues/594)
RUN apt-get update \
    && apt-get install -y build-essential python3-rosdep python3-catkin-lint python3-catkin-tools python3-osrf-pycommon \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN rosdep init && rosdep update 

# Create ROS workspace
COPY . /ws/src/mir_robot
WORKDIR /ws

# Use rosdep to install all dependencies (including ROS itself)
RUN DEBIAN_FRONTEND=noninteractive rosdep install --from-paths src -i -y --rosdistro noetic

RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && \
    catkin init && \
    catkin config --install -j 1 -p 1 && \
    catkin build --limit-status-rate 0.1 --no-notify && \
    catkin build --limit-status-rate 0.1 --no-notify --make-args tests"
