FROM ros:melodic-ros-core

RUN apt-get update \
    && apt-get install -y -qq --no-install-recommends build-essential python-catkin-tools python-rosdep cmake python-catkin-lint \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create ROS workspace
COPY . /ws/src/mir_robot
WORKDIR /ws

# Use rosdep to install all dependencies (including ROS itself)
RUN rosdep init && rosdep update && rosdep install --from-paths src -i -y --rosdistro melodic

RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && \
    catkin init && \
    catkin config --install -j 1 -p 1 && \
    catkin build --limit-status-rate 0.1 --no-notify && \
    catkin build --limit-status-rate 0.1 --no-notify --make-args tests"
