FROM ros:lunar-ros-core

RUN apt-get update && apt-get install -y \
    build-essential

# Create ROS workspace
COPY . /ws/src/mir_robot
WORKDIR /ws

# Install the package and its dependencies
RUN rosdep install --from-paths src --ignore-src --rosdistro lunar -y

# Set up the development environment
RUN /bin/bash -c "source /opt/ros/lunar/setup.bash && \
    catkin_make install"
