local_costmap:
    global_frame: $(arg prefix)odom
    static_map: false
    rolling_window: true
    raytrace_range: 6.0
    resolution: 0.05
    z_resolution: 0.15
    z_voxels: 8
    inflation:
      cost_scaling_factor: 10.0  # Exponential rate at which the obstacle cost drops off (default: 10). Must be chosen so that the cost value is > 0 at robot's circumscribed radius.
      inflation_radius:     0.6  # Max. distance from an obstacle at which costs are incurred for planning paths. Must be > robot's circumscribed radius.
    width: 4.0
    height: 4.0
    origin_x: 0.0
    origin_y: 0.0

    # plugins are loaded via costmap_local_params_plugins_[mapping|planning].yaml
