robot_base_frame: base_footprint
transform_tolerance: 0.4
update_frequency: 5.0
publish_frequency: 1.0
footprint: [[0.506,-0.32],[0.506,0.32],[-0.454,0.32],[-0.454,-0.32]]
footprint_padding: 0.0
obstacle_range: 3.0
#mark_threshold: 1
publish_voxel_map: true
navigation_map:
  map_topic: /map
#  first_map_only: true # set in costmap_params_[mapping|planning] to true/false
obstacles:
  observation_sources: b_scan_marking b_scan_clearing f_scan_marking f_scan_clearing
  b_scan_marking:
    topic: b_scan_rep117
    data_type: LaserScan
    clearing: false
    marking: true
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25
  b_scan_clearing:
    topic: b_scan_rep117
    data_type: LaserScan
    clearing: true
    marking: false
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25
  f_scan_marking:
    topic: f_scan_rep117
    data_type: LaserScan
    clearing: false
    marking: true
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25
  f_scan_clearing:
    topic: f_scan_rep117
    data_type: LaserScan
    clearing: true
    marking: false
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25
virtual_walls_map:
  map_topic: /virtual_walls/map
  first_map_only: true
  use_maximum: true
