<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- See https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-Diff-drive for ros2 information -->
  <xacro:macro name="diff_controller_plugin_gazebo" params="prefix ns left_wheel_joint right_wheel_joint wheel_separation wheel_radius">
    <gazebo>
      <!-- Use gazebo_ros_joint_state_publisher instead of publishWheelJointState -->
      <plugin name="joint_states" filename="libgazebo_ros_joint_state_publisher.so">
        <ros>
          <namespace>${ns}</namespace>
        </ros>
        <update_rate>1000.0</update_rate>
        <joint_name>${right_wheel_joint}</joint_name>
        <joint_name>${left_wheel_joint}</joint_name>
      </plugin>

      <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <ros>
          <remapping>cmd_vel:=${prefix}cmd_vel</remapping>
          <remapping>odom:=${prefix}odom</remapping>
        </ros>

        <legacy_mode>false</legacy_mode>
        <always_on>true</always_on>

        <update_rate>1000.0</update_rate>
        <left_joint>${left_wheel_joint}</left_joint>
        <right_joint>${right_wheel_joint}</right_joint>
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_diameter>${2*wheel_radius}</wheel_diameter>
        <odometry_frame>${prefix}odom</odometry_frame>

        <robot_base_frame>${prefix}base_footprint</robot_base_frame>
        <publish_odom>true</publish_odom>
        <publish_wheel_tf>false</publish_wheel_tf>
        <publish_odom_tf>true</publish_odom_tf>

        <max_wheel_torque>10</max_wheel_torque>
        <max_wheel_acceleration>2.8</max_wheel_acceleration>

      </plugin>
    </gazebo>
  </xacro:macro>

 <!-- See https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-P3D for ros2 information -->
  <xacro:macro name="p3d_base_controller" params="prefix">
    <gazebo>
      <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
        <ros>
          <remapping>odom:=${prefix}base_pose_ground_truth</remapping>
        </ros>
        <always_on>true</always_on>
        <update_rate>50.0</update_rate>
        <body_name>${prefix}base_footprint</body_name>
        <gaussian_noise>0.01</gaussian_noise>
        <frame_name>map</frame_name>
        <xyz_offset>0 0 0</xyz_offset>
        <rpy_offset>0 0 0</rpy_offset>
      </plugin>
    </gazebo>
  </xacro:macro>
</robot>
